### ISSUE TITLE
Improve whiteboard

### ISSUE THREAD

**Issue by bigabig** [uhh-lt/dwts#172]
- [x] Cannot create new whiteboard if my display is too small (also for analysis tables!)
- [x] Title of WB should depend on type / template of whiteboard
- [x] Duplicate whiteboard feature
- [x] Expand feature is not implemented for all objects
- [x] I want to see all whiteboard in the project, but i can only edit my own whiteboards
- [x] When adding cards, i want to choose where to put them
- [x] I want to edit WB name when it is open -> add edit button to wb title
- [x] Memo card misses an icon
- [x] I want to change the background color of db objects as well
- [x] I want to export the WB as image
- [x] select box to select multiple nodes
- [x] copy&paste of custom nodes
- [x] auto save every minute if there are changes
- [x] zoom far out to see everything (even if too small)
- [x] visually differentiate code, tag, annotation etc.

Rejected:
- [ ] virtual document for annotations instead of showing 1000 annotations per code -> Fundstellenausgabe
- [ ] show short annotations with some context
- [ ] configurable arrow directions of database links
- [ ] hover over memo/docs to show content
- [ ] hide expanded objects (button to toggle expand/hide). Reason: If edges are created between expanded objects, hiding those objects would delete corresponding objects. Way to complicated to implement

**Comment by floschne** [comment]
[ ] drag and drop codes -> merge
