### ISSUE TITLE
Backend thread pool is locked when handling more than 50 concurrent connections

### ISSUE THREAD

**Issue by raffomania** [uhh-lt/dwts#217]
During performance testing for the new authorization logic, I've ran into this issue: https://github.com/tiangolo/fastapi/issues/3205

Basically, when the backend has to handle more than 50 concurrent connections, everything grinds to a halt for 30 seconds, then a few requests error out and everything goes back to normal. 

[Here's a comment in the issue explaining why that happens](https://github.com/tiangolo/fastapi/issues/3205#issuecomment-974367848). 

The workaround it mentions seemed way too verbose for me, so I went looking and found [this section in the FastAPI docs](https://fastapi.tiangolo.com/tutorial/sql-databases/?h=sqlalchemy#about-def-vs-async-def). Basically, making all our endpoints and dependencies `def` instead of `async def` should resolve the issue. I've tested that, and it does seem to fix the problem! With the change, I can blast the backend with 500 concurrent requests for a continued time without it locking up :)

**Comment by floschne** [comment]
Oh, that's nice! Please open a PR with the changes :)

**Comment by raffomania** [comment]
As an alternative, switching to async sqlalchemy might be nice: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html

It would probably be more resource efficient than making endpoints blocking, but I'm not sure how stable sqlalchemy's support for async is.

**Comment by floschne** [comment]
Hm IDK. From my very first glance, it looks as if this would require many changes in the code + and much more complicated / "non-straight-forward" DB related thinking for future code

**Comment by floschne** [comment]
Also I think, 500 concurrent requests is more than enough (thinking of the scale we intend to reach)

**Comment by raffomania** [comment]
Alright, I'll go for the straightforward fix :) We'll still need to keep async in some endpoints that e.g. use the mail service, but I think that will be fine.

**Comment by raffomania** [comment]
This was fixed in #314 .
